import type { Metadata } from 'next'
import CodeBlock from '@/components/CodeBlock'

export const metadata: Metadata = { title: 'Core Concepts' }

export default function ConceptsPage() {
  return (
    <div className="doc-content">
      <p style={{ fontFamily: 'IBM Plex Mono', fontSize: '0.7rem', color: '#888', marginBottom: '0.5rem' }}>13 ——</p>
      <h1>Core Concepts</h1>

      <h2>The Blockchain Is Invisible</h2>
      <p>
        Automata&apos;s fundamental design principle is that users should think in money outcomes, not
        blockchain primitives. This manifests in every layer of the system:
      </p>
      <table>
        <thead><tr><th>Never say</th><th>Say instead</th></tr></thead>
        <tbody>
          <tr><td>gas fee</td><td>transfer fee / network fee</td></tr>
          <tr><td>bridge</td><td>move</td></tr>
          <tr><td>sign a transaction</td><td>confirm</td></tr>
          <tr><td>INSUFFICIENT_FUNDS 0x...</td><td>You don&apos;t have enough USDC on Base</td></tr>
          <tr><td>chain ID: 8453</td><td>(never shown)</td></tr>
          <tr><td>slippage</td><td>(never shown)</td></tr>
          <tr><td>contract address</td><td>(never shown)</td></tr>
          <tr><td>APY</td><td>% per year</td></tr>
          <tr><td>stake</td><td>deposit / earn</td></tr>
        </tbody>
      </table>

      <h2>Chat Interface vs Flow Builder</h2>
      <p>Two interfaces for two types of users:</p>

      <h3>Chat Interface (/chat)</h3>
      <p>
        The user types their intent in plain English. The agent reasons about it, calls tools, and
        returns either an informational response or a transaction plan. Designed for:
      </p>
      <ul>
        <li>New users who don&apos;t know the exact steps</li>
        <li>One-off transactions (&quot;Send 50 USDC to 0x...&quot;)</li>
        <li>Balance checks and market queries</li>
        <li>Multi-step flows that are hard to express as a sequence</li>
      </ul>

      <h3>Flow Builder (/build)</h3>
      <p>
        The user drags nodes onto a canvas and connects them. Designed for:
      </p>
      <ul>
        <li>Power users who want deterministic, repeatable sequences</li>
        <li>Saving and re-running named flows</li>
        <li>Visual inspection of complex multi-step strategies</li>
      </ul>

      <h2>Assisted vs Autonomous Execution</h2>

      <h3>Assisted Mode (default)</h3>
      <p>
        The agent listens, plans, and presents the full transaction sequence with fees before
        executing anything. The user reviews a <strong>transaction plan card</strong> showing:
      </p>
      <ul>
        <li>Each step in plain English</li>
        <li>Estimated fees</li>
        <li>Estimated time</li>
        <li>[ Confirm &amp; Sign ] and [ Cancel ] buttons</li>
      </ul>
      <p>
        Nothing is executed until the user explicitly confirms.
      </p>

      <h3>Autonomous Mode</h3>
      <p>
        The agent executes the sequence without a plan review step. The user still signs each
        wallet prompt (Privy requires this — the server never holds keys). Autonomous mode is
        appropriate for:
      </p>
      <ul>
        <li>Advanced users who understand what they&apos;re requesting</li>
        <li>Repeating a flow they&apos;ve reviewed before</li>
      </ul>

      <h2>The Unsigned Transaction Model</h2>
      <p>
        This is the core security design of Automata. The backend never has access to private keys
        and never submits transactions on the user&apos;s behalf.
      </p>
      <p>
        The flow is always:
      </p>
      <ol>
        <li>Backend builds the calldata (ABI-encoded function call)</li>
        <li>Backend returns the unsigned tx object in the API response</li>
        <li>Frontend shows it to the user in plain English</li>
        <li>User clicks Confirm</li>
        <li>Privy (or Stellar Wallets Kit) signs with the user&apos;s private key</li>
        <li>Frontend submits to the chain</li>
      </ol>
      <p>The server is a planner, not an executor. This distinction is absolute.</p>

      <h2>Session Model</h2>
      <p>
        A session is a conversation thread between the user and the Gemini agent. Each session:
      </p>
      <ul>
        <li>Is identified by a <code>sessionId</code> string generated by the frontend</li>
        <li>Stores a <code>ConversationMessage[]</code> — the accumulated dialogue history</li>
        <li>Is passed to Gemini on every request via <code>model.startChat(&#123; history &#125;)</code></li>
        <li>
          Is automatically deleted when the agent generates transactions — because the transaction
          replaces the conversation context
        </li>
        <li>Is stored in-memory (not persisted to DB in v2.0.0)</li>
      </ul>

      <h2>Wallet Address Routing</h2>
      <p>
        Because Stellar and EVM wallets have fundamentally different address formats, Automata
        tracks both separately. The frontend sends both addresses with every chat message:
      </p>
      <CodeBlock language="json">
{`{
  "message": "Swap XLM to USDC on Stellar",
  "walletAddress":  "0x1234...",   // EVM (from Privy)
  "stellarAddress": "GABC...",     // Stellar (from Stellar Wallets Kit)
  "geminiApiKey": "...",
  "sessionId": "..."
}`}
      </CodeBlock>
      <p>
        The backend injects both into the Gemini context as a prepended header, so the agent always
        knows which address to use for which chain.
      </p>
    </div>
  )
}
